services:
  app:
    build: .
    container_name: uniactivity_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - sqlite_data:/data
    restart: always

volumes:
  sqlite_data:
